server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/intern_selection_realm
  datasource:
    url: jdbc:mysql://localhost:3306/intern_selection_db
    username: user
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver


app:
  cors:
    allowed-origin: http://localhost:3000

keycloak:
  auth-url: http://localhost:8081
  realm: inst_idiomas_realm
  resource: springboot-app
